update rand to 0.8
mgeisler/lipsum pull request #68
Opened 2020-12-31 01:52 UTC by dancespiele

Hello:
* I updated rand to 0.8 
* I updated rand_chacha = "0.3"
* I update the code according with the new version of rand
* I fix all the issues which rust clippy complain

2021-01-03 19:16 UTC, mgeisler commented
Hi @dancespiele, wow, thanks very much for updating this!

I see you've put in a few other cleanups, could you please move them to other PRs? That will make it easier to see which changes are related to the rand 0.8 update and which are other (good) cleanups!

2021-01-03 19:19 UTC, mgeisler requested changes

2021-01-03 19:19 UTC, mgeisler commented on src/lib.rs
> +        self.keys.sort_unstable();
I believe this is unrelated to the update, so please submit this in a separate PR, thanks! Then you can explain there why this is a great change :smile:

2021-01-03 19:19 UTC, mgeisler commented on src/lib.rs
> -pub const LOREM_IPSUM: &'static str = include_str!("lorem-ipsum.txt");
Please also move this and the other lifetime changes to a separate PR. I guess they come from Clippy? I would be happy to clean this up, as long as they go in separately.

2021-01-03 19:19 UTC, mgeisler commented on src/lib.rs
> -            state: state,
Please put this back — I like the explicit field names since it matches the other lines.

2021-01-03 19:19 UTC, mgeisler commented on src/lib.rs
> -            rng: rng,
Please also put this line back.

2021-01-06 17:14 UTC, dancespiele commented
sorry for my late reply, I will try to change today

2021-01-07 02:04 UTC, dancespiele commented
I revert clean up, the changes that I didn't revert is required for the new version of rand 0.8

2021-01-09 13:03 UTC, mgeisler commented
> @mgeisler I reverted clean up, the change that I didn't revert is required for the new version of rand 0.8

This looks really great now, thank you very much! I'll merge this now and do a release soon.

2021-01-09 13:04 UTC, mgeisler approved these changes

2021-01-09 13:04 UTC, merged

2021-01-09 13:06 UTC, mgeisler commented on src/lib.rs
> -fn capitalize(word: &str) -> String {
It would be cool if you would submit this change as its own PR.

2021-01-09 13:06 UTC, mgeisler commented on src/lib.rs
> -pub const LOREM_IPSUM: &str = include_str!("lorem-ipsum.txt");
The removal of `'static` would also make a great PR.